# menus

purchase_menu: str = "\n1- Lista de todos os softwares \n2- Pesquisar um software \n3- Avaliar software"
companies_menu: str = "\n1- Buscar empresas cadastradas \n2- Fazer Cadastro \n3- Sair \n"
consultant_menu: str = "Cadastro de consultor\n 1- Para cadastrar novo consultor\n 2- Para sair"
home_menu: str = "\n1- Cadastrar-se \n2- Comprar software \n3- Quem somos \n4- Sair "
login_menu: str = "\n1- Cadastrar-se como cliente \n2- Cadastrar-se como empresa \n3- Cadastrar-se como consultor \n4- Cadastrar Software \n5- Sair \n"
more_menu: str = "\n1- Voltar pro menu principal \n2- Sair \n"
payment_menu: str = "\n1- Cartão de credito \n2- Cartão de debito \n3- Boleto \n4- Sair \n"
software_register_message: str = "Agora nos diga em qual categoria abaixo seu software se encaixa melhor: \n1- Saúde \n2- Educacional \n3- Empresarial \n4- Banco de dados \n5- Outros \n"
login: str = "\n1- Fazer Login \n2- Fazer Cadastro \n3- Sair"
purchase_complete_menu: str = "\n1- Comprar \n2- Desistir"
rate_menu: str = "Qual categoria de software voce quer avaliar: \n1- Saude \n2- Educacional \n3- Empresarial \n4- Banco de dados"

# common strings
cart_itens: str = "Os itens no seu carrinho de compras são: "
welcome: str = "\nBem vindo!"
age: str = "Digite sua idade: "
buy_register: str = "Para realizar o cadastro, informe os dados da empresa a seguir: "
card_due_date: str = "Digite a data de vencimento do cartão: "
card_name: str = "digite o nome impresso no cartao: "
card_number: str = "digite o numero do cartao: "
card_security_code: str = "digite o codigo de segurança do cartao: "
city: str = "Qual sua cidade: "
cnpj: str = "Digite seu CNPJ: "
cpf: str = "Digite seu CPF: "
district: str = "Qual seu bairro: "
email: str = "Digite seu e-mail: "
graduation: str = "Qual seu grau de formação: "
home_msg: str = "Escolhe de que forma voce pretende usar o nosso software:"
leaving_thanks: str = "Obrigado pela visita, esperamos ver você novamente!"
leaving_title: str = "Aparentemente você escolheu sair do nosso software, ou alguma selecionou uma opção invalida"
line: str = ("=" * 120)
loading_warning: str = "Aguarde uns segundos....."
location_msg: str = "Informe sua localização agora: "
more_details: str = "Python Bridge surgiu através ada necessidade um intermediador e um facilitador para empresas que procuram implantar sof-\ntwares.\nNossa equipe altamente dedicada e atensiosa tem como objetivo facilitar sua vida\ne lhe mostrar oque ha de melhor no mercado atual."
name: str = "Digite seu nome completo: "
ops: str = "Ops!"
option: str = "Digite a sua opção: "
other_type: str = "Qual tipo do seu software?"
payment_approved: str = "Transação aprovada!"
payment_failed: str = "Seus dados estão incompletos, tente novamente por favor!"
payment_message: str = "Obrigado pela preferencia! \nEscolha um dos metodos disponis para prosseguir com a sua compra!"
phone: str = "Digite o numero do seu telefone/celular: "
register_msg: str = "Informe os dados solicitados para fazer o seu cadastro: "
skills: str = "Quais são suas experiências na área da TI?"
software_info: str = "Faça um breve resumo de seu software: "
software_name: str = "Digite o nome do seu software: "
software_price: str = "Qual preço pretende vende-lo: "
software_thanks: str = "Obrigado por cadastrar seu software!"
state: str = "Digite o estado onde você mora: "
street: str = "Qual sua rua: "
street_number: str = "Qual o Nº da casa: "
ticket_message: str = "O pagamento é aprovado em até 3 dias uteis apos o pagamento do boleto!"
type_search: str = "Selecione a categoria do software que voce procura: \n1- Saúde \n2- Educacional \n3- Empresarial \n4- Banco de dados \n"
rate_description: str = "Digite sua avaliação para este software: "